package Proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: publicationProto.proto

public final class PublicationProtoOuterClass {
  private PublicationProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PublicationProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string company = 1;</code>
     * @return The company.
     */
    java.lang.String getCompany();
    /**
     * <code>string company = 1;</code>
     * @return The bytes for company.
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>double value = 2;</code>
     * @return The value.
     */
    double getValue();

    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     * @return The date.
     */
    com.google.protobuf.Timestamp getDate();
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

    /**
     * <code>double drop = 4;</code>
     * @return The drop.
     */
    double getDrop();

    /**
     * <code>double variation = 5;</code>
     * @return The variation.
     */
    double getVariation();
  }
  /**
   * Protobuf type {@code PublicationProto}
   */
  public static final class PublicationProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PublicationProto)
      PublicationProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PublicationProto.newBuilder() to construct.
    private PublicationProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublicationProto() {
      company_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PublicationProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PublicationProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              company_ = s;
              break;
            }
            case 17: {

              value_ = input.readDouble();
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (date_ != null) {
                subBuilder = date_.toBuilder();
              }
              date_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(date_);
                date_ = subBuilder.buildPartial();
              }

              break;
            }
            case 33: {

              drop_ = input.readDouble();
              break;
            }
            case 41: {

              variation_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicationProtoOuterClass.internal_static_PublicationProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicationProtoOuterClass.internal_static_PublicationProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublicationProtoOuterClass.PublicationProto.class, PublicationProtoOuterClass.PublicationProto.Builder.class);
    }

    public static final int COMPANY_FIELD_NUMBER = 1;
    private volatile java.lang.Object company_;
    /**
     * <code>string company = 1;</code>
     * @return The company.
     */
    @java.lang.Override
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <code>string company = 1;</code>
     * @return The bytes for company.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>double value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }

    public static final int DATE_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp date_;
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     * @return Whether the date field is set.
     */
    @java.lang.Override
    public boolean hasDate() {
      return date_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     * @return The date.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDate() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      return getDate();
    }

    public static final int DROP_FIELD_NUMBER = 4;
    private double drop_;
    /**
     * <code>double drop = 4;</code>
     * @return The drop.
     */
    @java.lang.Override
    public double getDrop() {
      return drop_;
    }

    public static final int VARIATION_FIELD_NUMBER = 5;
    private double variation_;
    /**
     * <code>double variation = 5;</code>
     * @return The variation.
     */
    @java.lang.Override
    public double getVariation() {
      return variation_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, company_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        output.writeDouble(2, value_);
      }
      if (date_ != null) {
        output.writeMessage(3, getDate());
      }
      if (java.lang.Double.doubleToRawLongBits(drop_) != 0) {
        output.writeDouble(4, drop_);
      }
      if (java.lang.Double.doubleToRawLongBits(variation_) != 0) {
        output.writeDouble(5, variation_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, company_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      if (date_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDate());
      }
      if (java.lang.Double.doubleToRawLongBits(drop_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, drop_);
      }
      if (java.lang.Double.doubleToRawLongBits(variation_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, variation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PublicationProtoOuterClass.PublicationProto)) {
        return super.equals(obj);
      }
      PublicationProtoOuterClass.PublicationProto other = (PublicationProtoOuterClass.PublicationProto) obj;

      if (!getCompany()
          .equals(other.getCompany())) return false;
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getDrop())
          != java.lang.Double.doubleToLongBits(
              other.getDrop())) return false;
      if (java.lang.Double.doubleToLongBits(getVariation())
          != java.lang.Double.doubleToLongBits(
              other.getVariation())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (37 * hash) + DROP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDrop()));
      hash = (37 * hash) + VARIATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVariation()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PublicationProtoOuterClass.PublicationProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PublicationProtoOuterClass.PublicationProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PublicationProtoOuterClass.PublicationProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PublicationProtoOuterClass.PublicationProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PublicationProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PublicationProto)
        PublicationProtoOuterClass.PublicationProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PublicationProtoOuterClass.internal_static_PublicationProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PublicationProtoOuterClass.internal_static_PublicationProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PublicationProtoOuterClass.PublicationProto.class, PublicationProtoOuterClass.PublicationProto.Builder.class);
      }

      // Construct using PublicationProtoOuterClass.PublicationProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        company_ = "";

        value_ = 0D;

        if (dateBuilder_ == null) {
          date_ = null;
        } else {
          date_ = null;
          dateBuilder_ = null;
        }
        drop_ = 0D;

        variation_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PublicationProtoOuterClass.internal_static_PublicationProto_descriptor;
      }

      @java.lang.Override
      public PublicationProtoOuterClass.PublicationProto getDefaultInstanceForType() {
        return PublicationProtoOuterClass.PublicationProto.getDefaultInstance();
      }

      @java.lang.Override
      public PublicationProtoOuterClass.PublicationProto build() {
        PublicationProtoOuterClass.PublicationProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PublicationProtoOuterClass.PublicationProto buildPartial() {
        PublicationProtoOuterClass.PublicationProto result = new PublicationProtoOuterClass.PublicationProto(this);
        result.company_ = company_;
        result.value_ = value_;
        if (dateBuilder_ == null) {
          result.date_ = date_;
        } else {
          result.date_ = dateBuilder_.build();
        }
        result.drop_ = drop_;
        result.variation_ = variation_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PublicationProtoOuterClass.PublicationProto) {
          return mergeFrom((PublicationProtoOuterClass.PublicationProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PublicationProtoOuterClass.PublicationProto other) {
        if (other == PublicationProtoOuterClass.PublicationProto.getDefaultInstance()) return this;
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          onChanged();
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        if (other.getDrop() != 0D) {
          setDrop(other.getDrop());
        }
        if (other.getVariation() != 0D) {
          setVariation(other.getVariation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PublicationProtoOuterClass.PublicationProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PublicationProtoOuterClass.PublicationProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <code>string company = 1;</code>
       * @return The company.
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string company = 1;</code>
       * @return The bytes for company.
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company = 1;</code>
       * @param value The company to set.
       * @return This builder for chaining.
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string company = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompany() {
        
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>string company = 1;</code>
       * @param value The bytes for company to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        company_ = value;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp date_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return dateBuilder_ != null || date_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       * @return The date.
       */
      public com.google.protobuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       */
      public Builder setDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
          onChanged();
        } else {
          dateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       */
      public Builder setDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
          onChanged();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       */
      public Builder mergeDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (date_ != null) {
            date_ =
              com.google.protobuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
          } else {
            date_ = value;
          }
          onChanged();
        } else {
          dateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       */
      public Builder clearDate() {
        if (dateBuilder_ == null) {
          date_ = null;
          onChanged();
        } else {
          date_ = null;
          dateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateBuilder() {
        
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }

      private double drop_ ;
      /**
       * <code>double drop = 4;</code>
       * @return The drop.
       */
      @java.lang.Override
      public double getDrop() {
        return drop_;
      }
      /**
       * <code>double drop = 4;</code>
       * @param value The drop to set.
       * @return This builder for chaining.
       */
      public Builder setDrop(double value) {
        
        drop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double drop = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDrop() {
        
        drop_ = 0D;
        onChanged();
        return this;
      }

      private double variation_ ;
      /**
       * <code>double variation = 5;</code>
       * @return The variation.
       */
      @java.lang.Override
      public double getVariation() {
        return variation_;
      }
      /**
       * <code>double variation = 5;</code>
       * @param value The variation to set.
       * @return This builder for chaining.
       */
      public Builder setVariation(double value) {
        
        variation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double variation = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVariation() {
        
        variation_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PublicationProto)
    }

    // @@protoc_insertion_point(class_scope:PublicationProto)
    private static final PublicationProtoOuterClass.PublicationProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PublicationProtoOuterClass.PublicationProto();
    }

    public static PublicationProtoOuterClass.PublicationProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicationProto>
        PARSER = new com.google.protobuf.AbstractParser<PublicationProto>() {
      @java.lang.Override
      public PublicationProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PublicationProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PublicationProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublicationProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PublicationProtoOuterClass.PublicationProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicationProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicationProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026publicationProto.proto\032\037google/protobu" +
      "f/timestamp.proto\"}\n\020PublicationProto\022\017\n" +
      "\007company\030\001 \001(\t\022\r\n\005value\030\002 \001(\001\022(\n\004date\030\003 " +
      "\001(\0132\032.google.protobuf.Timestamp\022\014\n\004drop\030" +
      "\004 \001(\001\022\021\n\tvariation\030\005 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_PublicationProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicationProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicationProto_descriptor,
        new java.lang.String[] { "Company", "Value", "Date", "Drop", "Variation", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
